# Site settings
title: "Bunch or random stuff"
author: "Luca Innocenti"
description: "Testing blog styles."
keywords: "Random"
biography: "I am me."
colophon: "Random blabla."

future: true

baseurl: ""
url: "http://hugosereno.eu"

github_username: lucainnocenti

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
