# Site settings
title: "Bunch or random stuff"
author: "Luca Innocenti"
description: "Testing blog styles."
keywords: "Random"
biography: "I am me."
colophon: "Random blabla."

future: true

baseurl: ""
url: "http://hugosereno.eu"

twitter_username: ferreira_hugo
github_username: hugoferreira
linkedin_username: hugoserenoferreira
facebook_username: hugo.sereno.ferreira
google-analytics: UA-69060-5

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
